include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - unawaited_futures
    - require_trailing_commas
    - prefer_final_locals
    - omit_local_variable_types
    - avoid_void_async
    - directives_ordering
    - sort_pub_dependencies
    - always_declare_return_types
    - prefer_const_constructors
    - avoid_unused_constructor_parameters